language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
script:
  - pytest
services:
  - sqlite
  - sonar-scanner
env:
  - DJANGO=2.2.6
addons:
  sonarcloud:
    organization: "borisv13-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token

